modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/nonamecrackers2/simple-clouds/issues" #optional

[[mods]]
	modId="${mod_id}"
	version="${mod_version}"
	displayName="${mod_name}"
	#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
	displayURL="https://modrinth.com/project/simple-clouds" #optional
	logoFile="simpleclouds.png" #optional
	#credits="" #optional
	authors="${mod_authors}" #optional
	#displayTest="NONE" # MATCH_VERSION is the default if nothing is specified (#optional)
	description='''${mod_description}'''

[[dependencies.${mod_id}]] #optional
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
    
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
    
[[dependencies.${mod_id}]]
    modId="crackerslib"
    mandatory=true
    versionRange="${crackerslib_version_range}"
    ordering="NONE"
    side="BOTH"